[workspace]
members = ["day*", "shared"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.76"

[workspace.dependencies]
anyhow = "1.0"
plotters = { version = "0.3.7", default-features = false, features = [
  "svg_backend",
  "line_series",
] }
