[package]
name = "day02"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { path = "../shared" }
anyhow = { workspace = true }

[[bench]]
name = "single_pass_vs_functional"
harness = false
