[package]
name = "day04"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { path = "../shared" }
anyhow = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
