[package]
name = "shared"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
plotters = { workspace = true }
criterion = { workspace = true }
serde_json = "1.0.140"
